### ISSUE TITLE
[feauture request] display light slider

### ISSUE THREAD

**Issue by forsterp** [Robz8/DSiMenuPlusPlus#101]
Hello together,

is it possible to implement such a feauture Maybe L+R+Right or L+R+Up. Always rebooting into normal System is a bit struggeling me.

Regards

**Comment by Robz8** [comment]
You can hold Select and then Vol - or + buttons to adjust screen backlight level.
This can be done even outside of CFW or DSiMenu++ itself.

**Comment by forsterp** [comment]
Also on o3ds xl? There is only a volume slider. Not your described Buttons. Can not bring it to work.

**Comment by Robz8** [comment]
Press HOME, and hold Select and then D-Pad Up/Down to adjust screen backlight level.

**Comment by vulpes-vulpeos** [comment]
hold start, not select :)

**Comment by thenets** [comment]
Wow! I never knew it!!
