### ISSUE TITLE
Crash when returning to menu

### ISSUE THREAD

**Issue by DerpBlerp** [Robz8/DSiMenuPlusPlus#103]
### Your console

Tell us which console do you have:

- [X]  Old 3DS XL

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release 1.1.0

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release 5.0.0

### Expected behaviour

Return to DSi menu ++ from game

### Actual behaviour

Console crashes after return combination is executed

### Steps to reproduce

1.Enter game
2.Input L+R+D-Pad Down+B for 2 seconds
3.The screens should turn black for couple secinds then the crash handler should appear.

**Comment by Robz8** [comment]
Enable game patching in Luma settings to fix the issue.
