### ISSUE TITLE
Icons for titles turn blank/vanish

### ISSUE THREAD

**Issue by M0RGaming** [Robz8/DSiMenuPlusPlus#106]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [X]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Out of 21 Icons, All icons should be visible.

### Actual behaviour

18 Are visible, 3 Are white, White icons include DSi Browser, Photo Clock, Flipnote Studios

### Steps to reproduce

Steps to reproduce are unknown however I can upload a video of what is happening if requested.

**Comment by Robz8** [comment]
Some animated DSi icons will appear white, due to the limitations of EasyGL2D.
To fix this, disable the animation in settings.

**Comment by M0RGaming** [comment]
Thanks
