### ISSUE TITLE
DS Download Play Functionality

### ISSUE THREAD

**Issue by ChromoTec** [Robz8/DSiMenuPlusPlus#110]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [x]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _[5.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

After selecting a "multiplayer" DS Download Play option in a DSiMenu++ game, other DS/DSi consoles should be able to connect to host DS/DSi console and play the game with them.

### Actual behaviour
Other DS/DSi consoles can connect, but do not finish downloading data, and "communication error occurred" message appears on host DS/DSi.

### Steps to reproduce

1. Open rom
2. Select multiplayer option
3. Open DS Download Play on secondary console
4. Connect to host console

### Additional Information

DS Download Play worked fine with all of my games (Marioparty DS, Super Mario 64 DS, Mariokart DS) but now it does not work with any of them. Other consoles can connect to mine when I use a physical copy of a game (to test, I used Mariokart DS).

**Comment by NoMod-Programming** [comment]
I'm pretty sure this is an ndsbootstrap issue, not a DSiMenuPlusPlus one.

**Comment by ChromoTec** [comment]
You are probably correct. However, I will keep this issue open until I get confirmation.

**Comment by legoj15** [comment]
This is a known nds-bootstrap issue afaik

**Comment by ChromoTec** [comment]
Ok, I guess this counts as the confirmation. If any of you have any idea how to fix it, head over to my issue on nds-bootstrap #319
