### ISSUE TITLE
L+R+DOWN+B for 2 seconds: Return to DSiMenu++.

### ISSUE THREAD

**Issue by jvhellraiser** [Robz8/DSiMenuPlusPlus#111]
This option is not working on Dsimenu++, when you press this combo Dsimenu++ try to go back to the menu screen where you boot the nds roms but it just stays there giving a black screen.

**Comment by DeathStarCommander** [comment]
Hi there, same here. Difference is that mine doesn't do anything. Curtently on Luma 3ds 9.0 and B9S 1.3

**Comment by jvhellraiser** [comment]
I think the info you want is LUMA3DS v7 iam pretty new to 3ds hacking and other stuff so sorry for being a noob. i have NTR CFW install in my 3ds as a side load CFW i guess thats how you call it only for the plugins. but thats all.

**Comment by Robz8** [comment]
If you have a9lh, then follow [this](https://3ds.hacks.guide/a9lh-to-b9s) guide.

**Comment by DeathStarCommander** [comment]
Robz8, we both have Luma. Is it any dsimenu++ error??

**Comment by Robz8** [comment]
No. It works fine for me.
Is game patching enabled in Luma settings?

**Comment by jvhellraiser** [comment]
Oh shit it actually work, no i did not had game Patching on LUMA settings thanks for noticing that.
