### ISSUE TITLE
No Icon on screen after installing CIA files with FBI.

### ISSUE THREAD

**Issue by CRCasey** [Robz8/DSiMenuPlusPlus#112]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by Robz8** [comment]
You have to install [this](https://github.com/Robz8/DSiMenuPlusPlus-Launcher/releases) to launch DSiMenu++ on 3DS.

**Comment by CRCasey** [comment]
Thanks for the heads up.  I didn't catch that step in the instructions.

**Comment by fennectech** [comment]
It 404s     where do i find that.

**Comment by RocketRobz** [comment]
You don't need the Launcher anymore.
Just install the latest TWiLight Menu++ version, and you'll be able to launch it from your 3DS HOME Menu.

**Comment by fennectech** [comment]
https://gbatemp.net/threads/ds-i-3ds-twilight-menu-gui-for-ds-i-games-and-ds-i-menu-replacement.472200/   The download link here links to this repo  I have downloaded the latest version as of last night and installed bolth CIAs   i still do not get an icon.

**Comment by RocketRobz** [comment]
Try rebooting the console.

**Comment by fennectech** [comment]
Nope    nothin

**Comment by RocketRobz** [comment]
Is there an error message you're getting when installing the CIA(s)?

**Comment by fennectech** [comment]
nope   They install fine and i can load them from the titles menu

**Comment by RocketRobz** [comment]
You probably have more than 40 DSiWare titles installed then.

**Comment by fennectech** [comment]
nope     No dsiware at all   Other than fieldrunners.

**Comment by fennectech** [comment]
Though when i launch the thing from the menu. I get this.   
![image](https://user-images.githubusercontent.com/11953665/51141152-02608700-180e-11e9-85ef-f7ef8baf6efa.jpg). And when i go back to the main menu and hit start it boots fine.   To this screen.

**Comment by fennectech** [comment]
This is what my DS I ware looks like.
