### ISSUE TITLE
Graphic glitches

### ISSUE THREAD

**Issue by hubert-skowronek** [Robz8/DSiMenuPlusPlus#114]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Latest release 1.1
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release 5.2
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

No flickering/glitched game icons/bar connecting icon with game's title label.

### Actual behaviour
Bottom screen has flickering horizontal line when scrolling through games list, some game icon are glitched sometimes (different ones each time, it's non-deterministic), the bar connecting icon with title label is glitched sometimes also (fragment of random game icon instead of it).

### Steps to reproduce

1. Load nds folder with more than dozen of games
2. Scroll constantly from left to right
3. Observe flickering, glitched bar, icons.

**Comment by Robz8** [comment]
Those bugs may not be fixed anytime soon, as they're probably from EasyGL2D.

**Comment by NightYoshi370** [comment]
"flickering is fixed, glitched icons are technically not fixed but their occurrence is pretty rare."

**Comment by flutterbrony** [comment]
I still have the bottom screen flickering on settings, home, and the emulator icons when I scroll from left to right. I don't have it when there is no games/folder where I scroll, or when all the icons fit on the screen but otherwise, everytime it's loading a new icon that wasn't displayed on the screen, it's still flickering.
