### ISSUE TITLE
Top Box arts and pixel perfect mode

### ISSUE THREAD

**Issue by Grendelia** [Robz8/DSiMenuPlusPlus#115]
Two things, first question, none of my top box arts are appearing on my games folder, can I auto download it? Second question on ds carts on 3ds you can hold I think start and you can boot into a pixel perfect mode, is that implamented into dsimenu++ or is it currently not there, sorry for the long message thank you!

**Comment by Robz8** [comment]
1. You can download the box art [here](https://gbatemp.net/threads/ds-i-3ds-dsimenu-ds-i-menu-replacement.472200/). Also, in the settings, make sure box art is set to be shown.
2. You can do that before DSiMenu++ starts.
