### ISSUE TITLE
I'm getting exception error when leaving settings

### ISSUE THREAD

**Issue by Dragonracer21** [Robz8/DSiMenuPlusPlus#117]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [x]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Latest release _[1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _[5.2.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

I'm getting an exception error occured screen when I leave the settings of dsimenu++. I also attached a photo with the error here.

### Steps to reproduce

1. start DSiMenu++
2. Go to the settings
3. Now leave them simply
![img_20180718_223124_727](https://user-images.githubusercontent.com/40526357/42906683-1dbd0c9a-8adc-11e8-9f6b-0c67a41ffce0.jpg)

**Comment by Robz8** [comment]
Turn on game patching in Luma settings to fix the issue.
