### ISSUE TITLE
[FEATURE REQUEST] Add support for usrcheat.dat

### ISSUE THREAD

**Issue by jvhellraiser** [Robz8/DSiMenuPlusPlus#119]
Dsimenu++ is looking great and thanks for your hard work, but the feature missing on Dsimenu++ is cheat support there some weird feelings between my R4 and Dsimenu++ in one way R4 ccan load nds + use usrcheat.dat file thats great but i have found in Dsimenu++ something great looks neat and it works i just feel that is missing that option is you can try to add usrcheat.dat option, thank you in advance.

**Comment by NightYoshi370** [comment]
Well, the cheats are handled via nds-bootstrap. You'd need to suggest that there

**Comment by piratesephiroth** [comment]
nah,  the cheats are handled by dsimenu++ and then added to nds-bootstrap.ini before it is launched.
