### ISSUE TITLE
Old3DS - Both key combos kick me back to 3DS Home Menu

### ISSUE THREAD

**Issue by DMSalesman** [Robz8/DSiMenuPlusPlus#121]
### Your console

Tell us which console do you have:

- [ ] DS Phat

- [ ] DS Lite

- [ ] DSi

- [ ] DSi XL

- [x] Old 3DS

- [ ] Old 3DS XL

- [ ] Old 2DS

- [ ] New 3DS

- [ ] New 3DS XL

- [ ] New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ] HiyaCFW

- [ ] Not using CFW / DSiWarehax

3DS/2DS:

- [x] Luma3DS

- [x] Rei-Six

- [ ] Other CFW [specify]

- [ ] Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x] >= 11.4

- [ ] < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x] Latest release _[v1.1.0]_

- [ ] I've compiled myself _[insert here commit hash]_

- [ ] Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x] Latest release _[v5.3.0 (Rev 01)]_

- [ ] I've compiled myself _[insert here commit hash]_

- [ ] Old release _[please specify version]_

### Expected behaviour

Have nds-bootstrap reload the loaded game upon inputting the `L + R + Start + Select` key combo; be sent back to DSiMenu++ when holding `L + R + Down + B` for two seconds.

### Actual behaviour

Upon inputting the `L + R + Start + Select` key combo or holding `L + R + Down + B` for two seconds, I get kicked back to the 3DS Home Menu after a brief wait. This happens on both Luma3DS and Rei-Six.

### Steps to reproduce

1. If using Luma3DS, ensure that `Enable game patching` be set;

2. Launch DSiMenu++;

3. Load an NDS game of your choice;

4. Wait for nds-boostrap to finish loading the game, then input the `L + R + Start + Select` key combo, or hold `L + R + Down + B` for two seconds.

**Comment by DMSalesman** [comment]
Would like to point out that, for some reason, your issue template didn't appear on my client.

**Comment by aatj887** [comment]
I have the same problem with the key combos. They just take me to the home menu even after updating all the stuff of DSiMenu++ and enabling game patching

**Comment by Robz8** [comment]
Closing, since this is a random occurrence for most users.

**Comment by DMSalesman** [comment]
@Robz8 I don't assume there's a way to log whatever happens when the combos are inputted, is it?

**Comment by Robz8** [comment]
nope
