### ISSUE TITLE
Glitched animated icon of Fire Emblem Heroes of Light and Shadow

### ISSUE THREAD

**Issue by hubert-skowronek** [Robz8/DSiMenuPlusPlus#123]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Latest release 1.1.0
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release 5.3.0
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Game's icon should be shown and animated properly.

### Actual behaviour

Some graphic noise is displayed instead of icon with the emblem.

### Steps to reproduce
Put Fire Emblem Heroes of Light and Shadow into SD card and turn on icon animations.

**Comment by Robz8** [comment]
Thanks for pointing out this issue.
Now that DSiMenu++ has NitroFS implementation, I'll certainly consider putting in the fixed banners/icons, like I did with TWLoader.

**Comment by hubert-skowronek** [comment]
Can't wait then :-)

**Comment by Robz8** [comment]
v5.3.1 now has the fixed icon.
