### ISSUE TITLE
Pokemon Freeze in New nintendo 2ds XL

### ISSUE THREAD

**Issue by DavidJoya** [Robz8/DSiMenuPlusPlus#124]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [*]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [*]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [*]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [*]  Latest release _v1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [*]  Latest release _[v5.2.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

###Expected behavior
play with normal heart golden pokemon

###Real behavior
After playing 15 or 20 minutes the video freezes but still plays the sound.

###Steps to play to play.
open DsiMenu ++, select the game and activate the saved game and after the time the video freezes

**Comment by Robz8** [comment]
You need to AP-patch the ROM.

**Comment by DavidJoya** [comment]
thank's, do you know how patch the ROM?
