### ISSUE TITLE
Saving Settings Issue/Reboot issue

### ISSUE THREAD

**Issue by DeanyBox** [Robz8/DSiMenuPlusPlus#125]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.7
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

Should re boot when changing ARM9 CPU Speed

### Actual behaviour

Tell us what happens instead

When saving setting it crashes and says an exception occured with a bunch of numbers.

### Steps to reproduce

1. Settings
2. ARM9 CPU Speed
3. Save Settings
4. Crashes

**Comment by Robz8** [comment]
Turn on game patching in Luma settings to fix the issue.

**Comment by DeanyBox** [comment]
okay thanks
