### ISSUE TITLE
start text glitches when scrolling back and forth through roms

### ISSUE THREAD

**Issue by YYoshi241** [Robz8/DSiMenuPlusPlus#129]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ X]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ X]  Latest release _[5.3.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X ]  Latest release _[1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

nothing
### Actual behaviour

Tell us what happens instead

glitches showing parts of game icons and not showing other game icons. START first turns red then game icon tiles replace it. even pressing select doesn't fix it
### Steps to reproduce

1.open dsimenu++
2.scroll back and forth through roms list (you may need 10+)
3.it happens

**Comment by Robz8** [comment]
It's an occasional bug that occurs, due to EasyGL2D being bugged.
It may not be fixed, unless another graphics lib is used, which may take work to switch over.

**Comment by YYoshi241** [comment]
By occasional you mean every time I use it. (or my 3ds is dumb, like why L+R+ST+SL doesn't work for me)

**Comment by Robz8** [comment]
Doesn't seem to occur on latest version.
