### ISSUE TITLE
Games with Special Characters in the Title Look Glitchy

### ISSUE THREAD

**Issue by RibShark** [Robz8/DSiMenuPlusPlus#13]
I'm running SRLoader on my Acekard 2i (as I cannot use TWLoader due to [this bug](https://github.com/Robz8/TWLoader/issues/347)). All of the Pokémon games (and I assume any others with special characters display incorrectly on both themes. On the DSi Menu theme. the é character seems to be replaced with the textures for the L/R button that display on the top screen (this also pushes the text outside of the box). On the Aura theme, the é is replaced with a two character wide black box that extends downwards about 5-6 lines worth of text.

**Comment by Robz8** [comment]
That's normal for now.
Currently, I have no idea how to fix that bug. :P

**Comment by Robz8** [comment]
The é bug has been fixed, by replacing it with a regular e.
The japanese characters are still glitched, though.

**Comment by Summerslyb** [comment]
Is there a plan for supporting CJK?

**Comment by Valkristh** [comment]
With the program dsbuff you can change de text displayed in Japanese or any games

**Comment by RonnChyran** [comment]
All Japanese characters should be UTF16. The encoding issue doesn't seem to be restricted to game titles, my DS profile name is in Japanese but it's garbled when displayed on the top left.
