### ISSUE TITLE
DSiMenu++ triggers system error after DS/DSi boot screen on  Old 2DS (FTR-001)

### ISSUE THREAD

**Issue by SuperGameCube** [Robz8/DSiMenuPlusPlus#132]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [0 ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [0 ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ 0]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ 0]  Latest release _[v5.3.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [0 ]  Latest release _[v5.3.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Should Boot into DSiMenu++ after DS/DSi Boot sequence.

### Actual behaviour

Gives system error asking me to turn the power off after
DS/DSi boot sequence, no error code give.

### Steps to reproduce

Sadly I don't know, everything seems to be the same when compared to set ups on the SD card
of people it's known to work for.

**Comment by myoKun345** [comment]
Same issue here, only with an old 3DS XL.

**Comment by NightYoshi370** [comment]
Have you tried a different CFW?

**Comment by NightYoshi370** [comment]
https://github.com/Robz8/DSiMenuPlusPlus/issues/134
Try the tutorial listed in this issue

**Comment by SuperGameCube** [comment]
DS/DSi Functionality was never broken in the first place, I've said so many
times that my DS games work even though this doesn't,
but since people seem to insist that I do, I did, and unsurprisingly it
didn't fix anything, and the result is the same, since DS/DSi functionality
wasn't broken to begin with.
Thanks for trying though, I appreciate it.

**Comment by SuperGameCube** [comment]
Here's an update though, I just downloaded the the latest version of DSi
Menu ++, and it works, just not the version I was using before, so it was
on DSiMenu++'s side of things all along, thanks for the help that was given,
I'm glad it finally works.

**Comment by NightYoshi370** [comment]
"DS/DSi Functionality was never broken in the first place, I've said so many
times that my DS games work even though this doesn't,
but since people seem to insist that I do, I did, and unsurprisingly it
didn't fix anything, and the result is the same, since DS/DSi functionality
wasn't broken to begin with.
Thanks for trying though, I appreciate it." Sorry, I didn't know

**Comment by NightYoshi370** [comment]
(Closing cause the issue was fixed)
