### ISSUE TITLE
System Settings .launcharg is incorrect

### ISSUE THREAD

**Issue by Epicpkmn11** [Robz8/DSiMenuPlusPlus#135]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [x]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _v5.3.1_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

System Settings opens

### Actual behaviour

It doesn't open and just goes back to DSiMenu++

This seems to be fixed by changing:
sd:/title/00030015/484e424a/content/00000002.app
to
sd:/title/00030015/484e424a/content/00000003.app
in the .launcharg (That's the Japanese one ^)

All regions except Australia have 00000002.app in the download, but (at least) Japanese and American consoles seem to want 00000003.app

### Steps to reproduce

1. Go to /roms/dsiware
2. Open System Settings
3. It doesn't open, unless you change the .launcharg to point to 00000003.app

**Comment by Robz8** [comment]
Fixed in v5.4.0.
