### ISSUE TITLE
I can not send Pokemon to Nintendo Wii through DSimenu ++ for Pokemon Battle Revolution. Every time I try it gets stuck on the white screen!

### ISSUE THREAD

**Issue by AlexHalley** [Robz8/DSiMenuPlusPlus#151]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1.
2.
3.

**Comment by AlexHalley** [comment]
I can not send Pokemon to Nintendo Wii through DSimenu ++ for Pokemon Battle Revolution. Every time I try it gets stuck on the white screen!

**Comment by Robz8** [comment]
It's normal for this to happen.
Also, please post this in the nds-bootstrap repo next time, as your posted issue is not related to DSiMenu++.

**Comment by AlexHalley** [comment]
Excuse me! I did not know where I should report this ... but since you showed up ... should you tell if this is possible someday or is it impossible or not in your priorities? (Dsimenu ++ communicating with the Nintendo Wii)

**Comment by Robz8** [comment]
I have no clue on how to get this working, though it should involve patching some functions.
