### ISSUE TITLE
L and R buttons have no function on DSi

### ISSUE THREAD

**Issue by Instandhaltung** [Robz8/DSiMenuPlusPlus#155]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [X]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[v5.4.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

L and R buttons should do something in the menu (I think, previous/next is written there)

### Actual behaviour

Buttons don't do anything

### Steps to reproduce

1. Press L and R on the DSiMenu++ while in menu screen

**Comment by Robz8** [comment]
They'll only work if you have more than 40 ROMs in the folder you're in.
That's why the previous/next text is written in gray.

**Comment by Instandhaltung** [comment]
Thanks for answering :)
