### ISSUE TITLE
Menu Music sounds scratchy (when heard on DSi speakers, at least)

### ISSUE THREAD

**Issue by Instandhaltung** [Robz8/DSiMenuPlusPlus#156]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [X]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[v5.4.1]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

I am unsure if this is normal, but the music sounds off and scratchy when there are loud notes. Is a low quality copy of the music used? Or am I imaginating things? I can't compare it to the original DSi menu anymore, right?

### Steps to reproduce

1. Listen to menu music on DSiMenu++

**Comment by Robz8** [comment]
It's normal. It's a low quality .wav file, so it can fit into RAM.

**Comment by Instandhaltung** [comment]
Is it impossible to improve? (It's not the original one, right?)

**Comment by Robz8** [comment]
May or may not be possible. (and no.)
