### ISSUE TITLE
Sound is way louder than the normal volume

### ISSUE THREAD

**Issue by ChampionLeake** [Robz8/DSiMenuPlusPlus#160]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4
- [x]  < 11.7

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

The sound is suppose to act normal

### Actual behaviour

The sound is killing my ears (It's louder than the usual volume)
You're not able to turn down the sound at all.

### Steps to reproduce

1. With default settings (Play any game)
2. Listen to the sound

**Comment by Robz8** [comment]
I never have this issue.
Have you tried installing the latest DSiMenu++ CIAs?

**Comment by ChampionLeake** [comment]
Nope

**Comment by Robz8** [comment]
Fixed in latest nds-bootstrap.
