### ISSUE TITLE
pokemon black/white battle freeze

### ISSUE THREAD

**Issue by pakrett** [Robz8/DSiMenuPlusPlus#161]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Latest release _[1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _[5.5.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

- On pokemon B/W, I start a battle with a trainer, I call my pokemon and it should appear and let me select a move to use.

### Actual behaviour

Tell us what happens instead

- On pokemon B/W, I start a battle with a trainer, I call my pokemon and it appear but the text that tell me which pokemon I have called is glitched (chinese/japanese caracter instead of french/english) then the game freeze and don't let me choose a move to use.
(This bug doesn't exist on DSiMenu++ 5.4.1)

### Steps to reproduce

1. Start pokemon B/W
2. Start a battle

**Comment by NightYoshi370** [comment]
Disable async prefetch.
Also, wrong repo
