### ISSUE TITLE
Arm9 exception when returning to DSi Menu++

### ISSUE THREAD

**Issue by YYoshi241** [Robz8/DSiMenuPlusPlus#163]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [X]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS (9.1)
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X]  >= 11.4 (11.7)
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release _[1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[5.5.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Return to dsimenu++

### Actual behaviour

Arm9 exception has occurred message

### Steps to reproduce

1.Launch ds rom
2.once loaded press & hold L+R+Down+Select
3.wait a few seconds then error

Notes: does not occur under dsi hb
And exception type is "prefetch abort (svcBreak)"

**Comment by Robz8** [comment]
Turn on game patching in Luma settings.
