### ISSUE TITLE
A little bug report

### ISSUE THREAD

**Issue by Valkristh** [Robz8/DSiMenuPlusPlus#164]
The touchscreen isn't working in gameyob after all and the new DSimenu++ version (5.5.1) isn't showed in settings. 
I'm using my DSi with hiyacfw + dsimenu++ and unlaunch 1.3

**Comment by YYoshi241** [comment]
On my 3ds in settings it says 5.5.0
But I just updated to latest. Haven't tested gameyob yet.

**Comment by Robz8** [comment]
@Valkristh You need to use the GameYob version that's included with DSiMenu++ v5.5.1, or just simply launch a GB/GBC/SGB ROM.
Touch works fine for me.

@YYoshi241 Redownload v5.5.1, as it now shows the correct version.

**Comment by Valkristh** [comment]
it's strange, that's what i used, the one include in dsimenu++ and i launched a game from the folder... i will redownload v5.5.1

**Comment by Robz8** [comment]
@Valkristh Can you post the MD5 checksum of your `gameyob.nds` file?
Check it by going to http://onlinemd5.com

**Comment by Valkristh** [comment]
Yes the page give me this 17EB0367DCA5D31CD51011814C883D36

**Comment by Robz8** [comment]
Same one for me. :P

Does touch work in the DSiMenu++ GUI?

**Comment by Valkristh** [comment]
In the gui yes

**Comment by Robz8** [comment]
@Valkristh Found that you need to enable touch in the Key Config of GameYob.
Press R to open the menu in GameYob.

**Comment by Valkristh** [comment]
Ok i did that, so the touch option now is menu... 
But i can't select any option, it's working like pressing R, just for open the menu

**Comment by Robz8** [comment]
That's normal. You can only set touch to do one thing, and in your case, it's opening the menu.
