### ISSUE TITLE
program shuts down when 3ds is closed

### ISSUE THREAD

**Issue by smudgehell** [Robz8/DSiMenuPlusPlus#166]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ x]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [ x]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

when the 3ds is closed the software idles and resumes upon opening again

### Actual behaviour

Tell us what happens instead

When the 3ds's clamshell is closed, the screen goes black and displays the sleep mode software closed screen

### Steps to reproduce

1.
2.
3.

**Comment by Robz8** [comment]
Does this issue occur in a ROM on the SD card, or the DSiMenu++ GUI?
If the first, then the issue should go in nds-bootstrap's repo.

**Comment by smudgehell** [comment]
oops... on the rom
