### ISSUE TITLE
Font and Crash Bug

### ISSUE THREAD

**Issue by Sha8q** [Robz8/DSiMenuPlusPlus#168]
This was done on my DSi with HiyaCFW.  I am using the latest version, 5.5.1.  When I first boot up DSiMenu++, the font is slightly more bold, and will fix itself when you move to another game.  Another problem is when I press Start, and in the menu with the 3 icons DSiMenu++ will crash if you press X on a blank icon.

**Comment by Robz8** [comment]
In the menu with the 3 icons, pressing X should bring you back to the DSi or 3DS menu, which is intended. There's no crash for me.
As for the bug with the font being slightly more bold, that bug I think will be fixed in the next version.

**Comment by Robz8** [comment]
Closing, as this issue is fixed in v6.1.0 and later versions.
