### ISSUE TITLE
Snes PLZZZ

### ISSUE THREAD

**Issue by jonaz8** [Robz8/DSiMenuPlusPlus#173]
can i play snes games in the DSiMenu++?

**Comment by yoyoyonono** [comment]
That's why you have emulators.

**Comment by jonaz8** [comment]
i don´t know how to load the snes emulator but i have it

**Comment by Stack3r** [comment]
These needs to be closed.

**Comment by catfatwm** [comment]
lol, yeah, i try to be professional on github, clearly this guy does too
