### ISSUE TITLE
Changing Settings crashes DSiMenu++

### ISSUE THREAD

**Issue by Kalanyr** [Robz8/DSiMenuPlusPlus#179]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [X]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release _[v1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[v6.0.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

When changing global settings , the settings are saved and DSiMenu++ soft resets.

### Actual behaviour

When changing global settings , the settings are saved and DSiMenu++ crashes to home menu. 

### Steps to reproduce

1. Press Start to access Global Settings.
2.  Change a Setting. 
3.  Exit the settings.

**Comment by Barawer** [comment]
Enable game patching in luma settings.

**Comment by dubbz82** [comment]
Game patching fixes reset when accessed via the button combo.  This sounds like something else....try wiping out the settings in file on the SD card and let dsimenu rebuild it maybe?

**Comment by Happin3ss** [comment]
I have the same problem before that will cause a soft-reset after saving the setting. But after trying to enable Game Patching in Luma3DS, the problem was **solved**. I can upload the crash log if S.O think It will help

**Comment by Robz8** [comment]
The issue with needing game patching has been fixed in the latest Luma commit.

**Comment by Kalanyr** [comment]
I think this may be because I'm using saltmode9 instead of B9S on my Australian N3DS XL , I return to home when I exit SD management instead of going back to settings as I believe I should. 

My US N3DS XL doesn't have this issue and it's running pure B9S, and it has the behaviour of returniing to settings instead of home when leaving SD management too.

**Comment by Kalanyr** [comment]
Yes, this is almost certainly a SaltMode and/or Luma issue , so I'll close this now.
