### ISSUE TITLE
Guru meditation error when opening a folder with the System Settings app

### ISSUE THREAD

**Issue by opm0** [Robz8/DSiMenuPlusPlus#181]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [X]  DSi, US region
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [X]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release (v6.0.0)
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

The folder should open and show the app's icon

### Actual behaviour

I get a red screen with a guru meditation error

### Steps to reproduce

1. Start DSiMenu++
2. Open a folder containing the system settings app

**Comment by Robz8** [comment]
It's possible that the .launcharg for the system settings app might have the incorrect path.
If it is correct, can you try swapping it with another .launcharg?

**Comment by opm0** [comment]
The path in the launcharg file is `sd:/title/00030015/484e4245/content/00000002.app`, but the file path on my SD card is `sd:/title/00030015/484e4245/content/0000000**3**.app` instead. I changed the path with a hex editor and now I can see the system settings app, but DSi apps send me back to DSiMenu++ and .nds roms freeze with a white screen.

**Comment by Robz8** [comment]
You need HiyaCFW installed to run .launcharg files and DS ROMs.
