### ISSUE TITLE
different launcher for every game

### ISSUE THREAD

**Issue by dwc56** [Robz8/DSiMenuPlusPlus#187]
i have a old 3ds on 11.2 running luma3ds i have to launch dsimenu++ from the main menu the select a game can i make a different launcher for every game so i select the game at the main menu?

**Comment by Robz8** [comment]
You may be looking for this.
https://gbatemp.net/threads/nds-forwarder-cias-for-your-home-menu.426174/

**Comment by NightYoshi370** [comment]
Closing since OP's question was answered
