### ISSUE TITLE
sd card corrupted

### ISSUE THREAD

**Issue by catfatwm** [Robz8/DSiMenuPlusPlus#189]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ x]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ x]  Latest release v6.1 (one posted on https://gbatemp.net/threads/ds-i-3ds-dsimenu-ds-i-menu-replacement.472200/page-135 or so)
 [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [ x]  Latest release v6.0
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen
upon opening a .nds file, game should create save file and load
### Actual behaviour

Tell us what happens instead
no save file was created, the game told me to restart the game, and game corrupted sd card. upon corrupting sd card, and then after fixing sd card using windows (fdisk i believe), all 3ds game icons were wrapped, and claimed to be downloaded from streetpass. had to rearrange all 300 icons.
### Steps to reproduce

1.open a game, when it says theres a problem with the save file, and to restart, use the l+r+\|/+b combo

if this is the wrong place for it i apologize, ive posted yesterday on reddit in the weekly issues/support on /r/3dshacks ive posted in the dsimenu++ v6.0 reddit page, and most recently on gbatemp. to be fair, i didnt wait very long after the gbatemp post to post here, and for that i apologize.

**Comment by Robz8** [comment]
The corruption of your SD card is not a DSiMenu++ issue. Your SD card might be dying.

**Comment by catfatwm** [comment]
ok, i appreciate everything you do. i wasnt posting this to complain, but in the hopes that it was a dsimenupp issue, it would help. thanks.
also, dsimenu++ is named because its in c++ or because its 1> than dsimenu?

**Comment by Robz8** [comment]
Because it's in C++, and also named after Explorer++ and Notepad++.

**Comment by catfatwm** [comment]
anyways, thanks robz
