### ISSUE TITLE
Theme-related White Screen

### ISSUE THREAD

**Issue by basicviralgoo** [Robz8/DSiMenuPlusPlus#199]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [x]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [x]  Latest release _2.0.2_
- [ ]  I've compiled myself
- [ ]  Old release

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _6.1.0_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

What should happen

Opening up a .nds file on any theme should work properly.

### Actual behaviour

Opening up any .nds file results in a white screen on the DSi, 3DS, and R4 themes. Acekard theme launches the files properly, so this isn't an issue with nds-bootstrap.

### Steps to reproduce

1. Open DSiMenu++ as normal with the launcher.
2. Select a theme other than Acekard.
3. Launch a .nds file

**Comment by NightYoshi370** [comment]
Have you tried using 6.1.1?

**Comment by NightYoshi370** [comment]
Actually, yeah, its fixed in 6.1.1.
Closing
