### ISSUE TITLE
Request: place to post custom akmenu themes for DSiMenu++

### ISSUE THREAD

**Issue by YYoshi241** [Robz8/DSiMenuPlusPlus#201]
Request: have an official issue (or repository) for custom acekard themes.

I'm not requesting that THIS ISSUE becomes that, however. Not that I care if it does.

If an issue for this is created, Reference that here and close this one.

**Comment by YYoshi241** [comment]
Another Request. But minor. 
Add Launch GBARunner2 to AK theme start menu.

**Comment by Robz8** [comment]
Already added.

**Comment by Valkristh** [comment]
I have some cool themes to add, i will post here xD

**Comment by NightYoshi370** [comment]
Well, the discord server just got a redesign, and I just asked the staff if they can make a channel. If shutterbug/any other admin makes one, I'll close this issue
