### ISSUE TITLE
I can´t switch between SD and Acekard

### ISSUE THREAD

**Issue by Darkshadow3582** [Robz8/DSiMenuPlusPlus#202]
if I try to change from SD to the flashcard by pressing up or down it does not detect it
I know it's still in beta, but I do not know if it's a bug or that flashcard is not yet implemented to that option

Thank for all hard work

**Comment by Robz8** [comment]
The flashcard isn't supported.

**Comment by Darkshadow3582** [comment]
So in the future, compatibility with that flashcard will be available, right?

**Comment by Robz8** [comment]
Probably not.
We've tested other flashcards, and they make DSiMenu++ crash when trying to init the DLDI driver for them.
The only flashcard compabile for switching to atm, is the R4 Ultra (with the www.r4ultra.com URL).
