### ISSUE TITLE
Blank Screen After playing Any game

### ISSUE THREAD

**Issue by LaytoMax35** [Robz8/DSiMenuPlusPlus#204]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [x ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ x]  Latest release _[6.0.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [ ]  Latest release _[2050 (2.0.2)]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Game starting sucefully
### Actual behaviour

Whenever i open any nds game it just led to a blank screen,if i however open dsimenu++from itself it boots just fine
### Steps to reproduce

1.Start dsimenu++
2.Open a game

**Comment by Robz8** [comment]
It's normal for this version. Wait for the next version to release.
Also, you reversed the DSiMenu++ and Launcher versions.

**Comment by LaytoMax35** [comment]
Sorry about the versions,and anyway isnt there anything i can do?maybe try the beta release or something?

**Comment by Robz8** [comment]
Oh, I misread 6.0.0 as 6.1.0, which is the latest, and has the issue where pressing select to open per-game settings, causes an error.

**Comment by LaytoMax35** [comment]
i dont press select to open per game settings,i just try to normally launch a game

**Comment by LaytoMax35** [comment]
and i though 6.1.0 didnt counted as it was a beta

**Comment by Robz8** [comment]
Wait for the next version to be released.

**Comment by LaytoMax35** [comment]
but,do you know why dsimenu++ works for some people and it doesnt for others?

**Comment by Robz8** [comment]
Probably differences in `settings.ini` or the hardware.

**Comment by LaytoMax35** [comment]
so,theres no way i cant change settings.ini right?
i really need to play dsi games :/

**Comment by Robz8** [comment]
v6.1.1 is released. Try that version.

**Comment by LaytoMax35** [comment]
it fixed the issue,thank you so much for the support @Robz8
