### ISSUE TITLE
NTR clock speed instead uses TWL, and vice-versa

### ISSUE THREAD

**Issue by dogtopus** [Robz8/DSiMenuPlusPlus#211]
### Your console

Tell us which console do you have:

- [ ]  DS Phat/Lite
- [ ]  DSi (XL)
- [X]  Old 3DS/2DS (XL)
- [ ]  New 3DS/2DS (XL)

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / Unlaunch only
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Release _[v2.0.2]_
- [ ]  Nightly _[insert here commit hash]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Release _[v6.2.0]_
- [ ]  Nightly _[insert here commit hash]_

### Expected behaviour

Slot-1 should boot to faster 133MHz mode like it was on TWLoader

### Actual behaviour

Slot-1 boots to the slower 66MHz mode instead

### Steps to reproduce

1. In DSiMenu++, set mode to DSi and clock speed to 133MHz mode
2. Boot Slot-1 flashcart
3. In flashcart, boot a CPU-intensive application. In my case I use moonshell to play an moderate bitrate OGG file.
4. Watch it choke instead of running smoothly like it was on TWLoader

**Comment by Robz8** [comment]
Strange. I thought I fixed that issue, but somehow, it's broken again.

**Comment by Robz8** [comment]
Ok, it actually works, but to use TWL clock speed, you have to set NTR clock speed in the settings.
That issue will be fixed in the next version.

**Comment by Robz8** [comment]
Fixed in v6.2.1.

**Comment by dogtopus** [comment]
Whoa that was fast :O
