### ISSUE TITLE
Request: Simple Feature tracker/Progress list.

### ISSUE THREAD

**Issue by Xeddius** [Robz8/DSiMenuPlusPlus#27]
Some homebrew .nds files do not launch or have whitescreen issues. (dldi patching stuff???)
Could we set up a tracker for DSi titles that work or do not work (I'm willing to test multiple titles, log, report, update and maintain a tracker/wiki/spreadsheet for them. *Specifically on DSi as the games which launch on TWLoader do not always seem to work with SRLoader*)

Also, any progress on wireless functionality?

**Comment by Xeddius** [comment]
The homebrew roms list doesn't seem to be showing any text but does have some green, blue, and red boxes. The other tabs work fine and show text, but for some reason dsi homebrew is blank.

**Comment by Lykie** [comment]
That's because no one's working on the list. You can request access to work on filling the compatibility list by clicking the "View Only" button and then "Request Edit Access."

**Comment by NightYoshi370** [comment]
For the first one, you would need a .xml thingy, that will need to be updated every time you update nds-bootstrap. I don't think the hassle is worth it. not only the fact that it would need to be updated, but the developers simply can't test every game out there.

As for the second one, that's relating to nds-bootstrap, not DSiMenu++.

Closing this
