### ISSUE TITLE
DS Download Play/Multiplayer issues.

### ISSUE THREAD

**Issue by Xeddius** [Robz8/DSiMenuPlusPlus#32]
So far none of the games I've loaded seem to be able to use the DS download play feature as it just brings up an error or never shows up on the other devices. Tested with both 3DS and DSi. Does the download play feature not work yet?

Edit: Mario Kart DS works with TWLoader, so maybe it's rom specific. Kirby Super Star Ultra doesn't support ds download play as of right now. (even though it said there was a communication error with mkds and the other system never got past the nintendo logo.) Mkds freezes on "Multiplayer" with the latest SRLoader on DSi

**Comment by Robz8** [comment]
On 3DS, only Download Play works on games that use SDK5/TWLSDK.
On both systems, Download Play does not work for SDK1-4 games.

**Comment by Xeddius** [comment]
I see, is this a permanent thing or just a temporary issue until it can be patched?


Side note: do you think it'd be possible to launch pictochat and download play from the twloader menu on 3ds?

**Comment by Robz8** [comment]
We're hoping this can be fixed.

Also, yes, they should work as both .nds and .cia files.

**Comment by Xeddius** [comment]
Awesome, I've managed to get pictochat working. I've been trying to get access to the spreadsheet to add SRLoader games that do and do not run, but nobody has replied or anything, so I might start a thread in a new issue just for reporting what games do and do not run and what bugs and settings are being used. It's a shame the DSi brew community is still so small.

**Comment by Robz8** [comment]
You should be able to edit the list now.

**Comment by NightYoshi370** [comment]
@Robz8 This isn't a DSiMenu++ issue. This is an issue with nds-bootstrap. This should be closed IMO
