### ISSUE TITLE
Working and Non-Working titles thread. (Come here to report which games work and which don't)

### ISSUE THREAD

**Issue by Xeddius** [Robz8/DSiMenuPlusPlus#33]
Posting format rules are as follows

Game: 
Region:
Bootstrap:
Donor Rom:
Clockspeed:
Console:
SRLoader Version:
Issues:

**Example:** (also a legit first entry as of writing.)
>Game: "Mega Man Battle Network 5 Double Team DS"
Region: U
Bootstrap: Unofficial and Release
Donor Rom: MKDS
Clockspeed: NTR and TWL
Console:DSi
SRLoader Version:3.4.2
Issues: White screen until reset.

**Comment by Robz8** [comment]
We already have a bootstrap compatibility list. 
:P https://docs.google.com/spreadsheets/d/1M7MxYQzVhb4604esdvo57a7crSvbGzFIdotLW0bm0Co/edit#gid=0

**Comment by Xeddius** [comment]
Yes, and nobody is working on the DSi portion along with the fact that I can't edit or update it despite the fact that I'm more than willing to put in the effort. :/

**Comment by Robz8** [comment]
I *think* I've granted you access. Not sure, though.

**Comment by Xeddius** [comment]
If possible can we keep this thread open as a place for people to post DSi results? I'll maintain the DSi portion.

**Comment by Xeddius** [comment]
It's pretty nice, but the layout is too large for my screen and it's frustrating to use when half of the screen is being taken up by the layout alone. I'll contribute to both lists when I get the chance, I just got 15 new cartridges to backup and test, so I'll be adding those soon.
