### ISSUE TITLE
[Feature Request] Option for .dsv saves for DeSmuMe cross compatibility

### ISSUE THREAD

**Issue by RandomMan25XX** [Robz8/DSiMenuPlusPlus#47]
As suggested by favna in the server, an option like this would be a possible idea for those that like to play ds games on pc and 3ds via this loader (obviously after SDK 3-5 saving to sd is sorted and whatnot), this can be an idea to leave on the backburner for a while or until someone decides to fork the repository and merge the new code

**Comment by Robz8** [comment]
They're already compatible. Just rename .dsv to .sav.
