### ISSUE TITLE
Return to DSiMenu++ Crashing N3DS

### ISSUE THREAD

**Issue by DarkDengar** [Robz8/DSiMenuPlusPlus#49]
_Apologies if this is the wrong repository to post this issue; this feature was mentioned in the main forum posting on GBATemp for this application, so I decided to go with this one over nds-bootstrap._

Using nds-bootstrap 0.8.1, DSiMenu++ (CIA) 4.2.0 on N3DS XL 11.6-39U and Luma CFW 9.0.

The new "Return to DSiMenu++" feature is crashing on me. I have tried using it on many DS games launched through DSiMenu++ with no luck. Does this happen to anyone else?

What happens:
After holding L+R+DOWN_DPAD+B buttons for a couple of seconds, the screen goes black as expected. However, after a few more seconds, instead of returning to DSiMenu++, the 3DS prints a crash dump, which I have attached.
[crash_dump_00000027.dmp.zip](https://github.com/Robz8/DSiMenuPlusPlus/files/2106990/crash_dump_00000027.dmp.zip)

Some quick details from the crash dump screen (crashed after trying this feature to return to DSiMenu++ from Super Mario 64 DS played fully from SD card) as an example:

```
Processor: ARM11 (core 1)
Exception type: prefetch abort (svcBreak)
Fault status: Debug event
Current process: ns (0004013000008002)
```

**Comment by Robz8** [comment]
Try the latest unofficial bootstrap build from here: https://github.com/Robz8/DSiMenuPlusPlus-update
then switch bootstrap to unofficial in the settings.

If you still get the crash screen after doing that, then idk what to do, as I also have this issue.

**Comment by Multimegamander** [comment]
BuT cAn ThE dSi RuN fOrTnItE?
