### ISSUE TITLE
Blank White Screen When Booting any Game

### ISSUE THREAD

**Issue by NintendoHacker44** [Robz8/DSiMenuPlusPlus#50]
I am using DSiMenu++ on my 3DS, whith the lates nds-bootstrap (3DS Version) and when ever I try to play a game, I just get a plain white screen.

**Comment by NintendoHacker44** [comment]
Nvm...

**Comment by Laqueeshous** [comment]
how did u fix it, im having this issue and cant find a fix

**Comment by Robz8** [comment]
What game are you trying to play?

**Comment by Laqueeshous** [comment]
I have tried Zelda Phantom Hourglass, Spirit Tracks, and Pokémon Soulsilver. I imagined The 2 Zelda games may not be compatible at the moment, but SoulSilver I dont know because I have launched it before, but once I reinstalled DsiMenu++ and nds-bootstrap none of them will work

**Comment by Robz8** [comment]
Both Zelda games are compatible.
Try turning off async prefetch.

**Comment by Laqueeshous** [comment]
How do I do that?

**Comment by Robz8** [comment]
Go into DSiMenu++ settings.

**Comment by Laqueeshous** [comment]
I dont see that option anywhere

**Comment by Robz8** [comment]
What version is your DSiMenu++?

**Comment by Laqueeshous** [comment]
v5.3.1

**Comment by Robz8** [comment]
The option should be in the Games/Apps settings.

**Comment by Laqueeshous** [comment]
oh i didnt know i could press L or R to switch pages in the settings menu i thought GUI settings was the only menu, sorry im dumb thank u so much man

**Comment by Laqueeshous** [comment]
nvm it didnt work im still getting the same white screen

**Comment by Sawyer-boy** [comment]
I think I had a similar problem. My dsi ++ menu was not starting, just a white screen (I use a DSiXL and Dsimenu ++ is my direct boot), then I took the SD card, I normally went into the DSi menu and went to the camera, after I opened it, put the SD card again and accessed through the application. After that, when I restarted dsi, everything went back to normal. If you want to try.

**Comment by DeathTBO** [comment]
I am having this issue as well. I've used both 5.5.0 and 5.5.1. When I attempt to launch Zelda Phantom Hourglass it goes through a loading period, then proceeds to a white screen. The system isn't frozen, and I can use the home button to get back to the main menu. Async prefetch on/off makes no difference.

This ONLY affects Zelda: Phantom Hourglass. I tested a bunch of games, including another Zelda game and they all work without a hitch.

Working Games:

Zelda: Spirit Tracks
Phoenix Wright Ace Attorney (DS)
Phoenix Wright Ace Attorney: Justice For All (DS)
Pokemon: Black 2
ChronoTrigger (DS)

On a side note, every time I enter the settings menu then leave it freezes the system on a black screen. I have to hold the power to turn it off. The settings still save.

**Comment by Robz8** [comment]
nds-bootstrap v0.11.0 isn't quite stable, as it broke compatibility with some games.

**Comment by DeathTBO** [comment]
Alright thanks for the quick response. I was racking my brain because the rom worked fine on DeSmuME, and my other roms were working flawlessly.

Game patching in Luma fixed the black screen issue.

**Comment by Musana229** [comment]
Anyone got an idea why phantom hourglass is not working?

**Comment by Robz8** [comment]
Try updating nds-bootstrap.

**Comment by VerminialFalcon** [comment]
I'm having the same problem, I'm trying to run Jump Ultimate Stars but it comes as a white screen, other games like Super Mario 64 work.

**Comment by Robz8** [comment]
Repack the Jump Ultimate Stars ROM using DSLazy.

**Comment by EinUnknown** [comment]
I had the similar problems with all of my Professor Layton Games (Europe Version).
I turned the "Debug" Option on so maybe I can see the error.
As I started the games, the Dubugger says multiple times that I have to press the Start Button to continue.
After that, all my games were able to boot!
I hope, this helps some of you!

**Comment by chrispsebasp** [comment]
I have the same problem, i started with pokemon soulsilver, new super mario bros and when i press any game, it gets the white screen, i have bootstrap v0.12.1, and the dsimenu++ v6.2.1

**Comment by chrispsebasp** [comment]
I dont know what to do

**Comment by Robz8** [comment]
Try re-downloading latest nds-bootstrap.

**Comment by chrispsebasp** [comment]
thanks man, you´re a machine

**Comment by chrispsebasp** [comment]
Now i have another problem, when i play pokemon soulsilver, sometimes when i talk or before i enter a battle it crashes

**Comment by Stack3r** [comment]
Turn off vram and make sure you are running in ds mode, no issues here 100% cart speed for HGSS

**Comment by chrispsebasp** [comment]
its like 10 minutes of normal playing a then when i battle or enter to a place, it freezes

**Comment by Robz8** [comment]
Is the ROM AP-patched?

**Comment by chrispsebasp** [comment]
ýes

**Comment by chrispsebasp** [comment]
i dont know if i have to patch it with other method, but its patched, also when i try to patch it, shows an error

**Comment by Robz8** [comment]
Use DS Scene ROM Tool to patch it.

**Comment by pakrett** [comment]
I have some issues with nds bootstrap 0.12.x I came back to 0.11.2 and all is working again.
