### ISSUE TITLE
Touchscreen not working

### ISSUE THREAD

**Issue by oGamefreak** [Robz8/DSiMenuPlusPlus#51]
Originally I couldn't launch a NDS rom or it would kick me to the 3ds menu. I then turned on Quick-start ROM and I could launch the NDS rom but now the touch screen in games does not work. I am on a n3ds if that matters at all.

**Comment by Robz8** [comment]
Have you tried the latest nds-bootstrap version?

**Comment by oGamefreak** [comment]
Yup. I can only get the touch screen to work if I launch the game, go back to the 3ds home menu, and then choose load last rom from the four options shown at the boot menu. I'm on v0.9.0-RC2 of nds-bootstrap

**Comment by Robz8** [comment]
Try installing the latest DSiMenu++ CIAs and latest nds-bootstrap.
