### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by autofire372** [Robz8/DSiMenuPlusPlus#52]
`C:/Emulation/3DS/DSiMenuPlusPlus/romsel_r4theme/arm9/source/graphics/fontHandler.cpp:32:10: fatal error: large_font.h: No such file or directory`

Getting the above error when compiling from latest source. I can't figure out what's wrong. Am I missing a dependency?

**Comment by piratesephiroth** [comment]
copy `large_font.bmp` and `large_font.grit` from `\romsel_dsimenutheme\gfx` to `\romsel_r4theme\gfx`

**Comment by autofire372** [comment]
After fixing those I ran into another issue: the patch_ndsheader_dsiware python scripts are seemingly broken, complaining about missing parentheses when they try to execute.

**Comment by Robz8** [comment]
Don't worry about that.
