### ISSUE TITLE
Nothing Works?

### ISSUE THREAD

**Issue by RinMaru** [Robz8/DSiMenuPlusPlus#54]
After Deleting TWLoader and its extensions from twlnand I downloaded this. Unfortunately No games run like they used to in TWLoader. if I set it to TWL speed all games will kick me back to the 3DS menu. If I use NTR speed ill get errors such as with Super Mario 64 DS "Startup Error 1" 

N3DS Latest Firmware and B9S Luma3DS Latest

**Comment by mariogamer2** [comment]
You need to activate quick-start ROM.

**Comment by RinMaru** [comment]
That doesn't fix anything now I just get a white screen

**Comment by RinMaru** [comment]
ill close this it seems to work with latest nds bootstrap
