### ISSUE TITLE
[Feature Request] Updater

### ISSUE THREAD

**Issue by RinMaru** [Robz8/DSiMenuPlusPlus#57]
Would it Be Possible to have an Update Option for DSiMenu++ & nds_bootstrap?

**Comment by Robz8** [comment]
Yes, it's been planned for a while.

**Comment by piratesephiroth** [comment]
because the CIA doesn't install the program, only the supporting files

**Comment by NightYoshi370** [comment]
This isn't something that can be implemented inside DSiMenu++ without some major complications. Rather, this would be implemented within the DSiMenu++ launcher, which can be found here: https://github.com/Robz8/DSiMenuPlusPlus-Launcher

I'm not sure if I should close this or not.

**Comment by RinMaru** [comment]
its being implemented in DSiMenu++ Launcher so ill close this
