### ISSUE TITLE
Black Screen and reboot on New3DS/2DS

### ISSUE THREAD

**Issue by WalaRocks18** [Robz8/DSiMenuPlusPlus#58]
I deleted TWLoader and all its associates and installed DSi Menu ++.
I opened games and then tried to load them and it didn't work, it just resets and sends me to 3DS home screen, the console doesn't crash but it doesn't have the same compatibility as TWLoader i think. And yes, i tried uninstalling and reinstalling and change from NTR to TWL.
I also have the latest version of DSiMenu++(4.2.0) and it's launcher too(1.1.0).

                                                                                plz` halp.

**Comment by RinMaru** [comment]
Use the latest nds bootstrap

**Comment by WalaRocks18** [comment]
nope, didn't work

**Comment by RinMaru** [comment]
did you enable quickstart?

**Comment by WalaRocks18** [comment]
yes, it didn't work, well ill just stay with TWLoader u til this is fixed, see ya!

**Comment by WalaRocks18** [comment]
i think i will close this

**Comment by Robz8** [comment]
What do you mean "didn't work"?
Can you explain what happens after you set "Quick-start ROM"?

**Comment by WalaRocks18** [comment]
nothing, it doesn't matter, i already fixed it

**Comment by Robz8** [comment]
Ah, ok.

**Comment by piratesephiroth** [comment]
that's what I was about to suggest, something with the SD card

**Comment by chimel23** [comment]
I gave old 3DS and the same problem. Why won’t the games start?
