### ISSUE TITLE
Pokémon HeartGold/SoulSilver crashes 

### ISSUE THREAD

**Issue by WalaRocks18** [Robz8/DSiMenuPlusPlus#59]
While playing for a bit, the games just tends to crash all of the sudden.
The music keeps going but the game stops dead

@Robz8 and @ahezard plz fix

PD: is it a memory problem?

**Comment by Robz8** [comment]
It's an AP problem.
Try patching your ROM with an AP patch.

**Comment by WalaRocks18** [comment]
ok then thanks

**Comment by WalaRocks18** [comment]
Surprise surprise!

it didn't work, still crashes like 10 min or less in game, can you provide a link to it (Game patch or patched)?
That would be very helpful.

**Comment by piratesephiroth** [comment]
have did you tried this?

https://filetrip.net/nds-downloads/rom-hacks/download-pkm-black-and-white-rudolfs-patch-r4-1-6-f13003.html

**Comment by forsterp** [comment]
Ok so I have the same Problems. Just updated all. Bootstrap 0.9.2, DSiMenu++ 4.3.1rev1 and Launcher 1.1.0. I get a black screen all 10-15min when changeching the room or a new Scene begin. Musik don't stop. On PC the roms are working great. Tried different patches all same issue. For Soulsilver(G) my CRC32 are 59D6AC6F and with patch 94E4A5B5. Still same Problems. If you Need addional Infos About my files feel free to ask.

**Comment by WalaRocks18** [comment]
And it doesn't work on 0.9.2, it crashes

**Comment by WalaRocks18** [comment]
Hey @forsterp i can send u them files of PkMn HG if u like and try playing in 0.9.1 rev1, cuz it doesn't work on the latest.

**Comment by forsterp** [comment]
Would be really cool if you can discribe what you have done. So I can patch my GERMAN roms as well. And to understand the technical background is also nice. Feel free to contact me on discord sword#0474

**Comment by WalaRocks18** [comment]
Sorry @forsterp couldn't fix it i tried with a spanish version of HG and it kept crashing anyways.
I don't think is possible to find a patch for the EU releases and if anyone has it, i don't think they would notice this post. So i can't deal with it, sorry.

¯\_(ツ)_/¯

**Comment by WalaRocks18** [comment]
but ill send u a link to mein games link:http://www.mediafire.com/folder/g74cwmtp5ltqi/PkMnHGAPpatched

**Comment by forsterp** [comment]
Allready have a Copyright claime and cant be downloaded Maybe zip it. @Robz8 did you have some tipps for us?

**Comment by WalaRocks18** [comment]
https://drive.google.com/open?id=138vDMTNvPGQsg34V0OvxLyTOaxl1tgY2
https://drive.google.com/open?id=1UCUkPQslZyKzts6xz8N2WrUzYoYN9N5M

**Comment by WalaRocks18** [comment]
there, gdrive

**Comment by forsterp** [comment]
thank you

**Comment by WalaRocks18** [comment]
try it in 0.9.1rev1 bootstrap, cuz 0.9.2 is broken

**Comment by forsterp** [comment]
http://www.ds-scene.net/?s=viewtopic&nid=11056 have fun

**Comment by WalaRocks18** [comment]
thank you miraculous man!

**Comment by TADebastiani** [comment]
Hi guys, I have the same problem of @forsterp and @WalaRocks18 with Pkmn Heart Gold, the game crashse about 10 minutes and occours an error when load the save.
I used the latest version of *DS-Scene Rom Tool* to path, but didn't work.
I have the *DSiMenuPlusPlus v5.3.1* with *nds-bootstrap v0.10.2*.
Any help?

**Comment by TADebastiani** [comment]
Hi guys, I have the same problem of @forsterp and @WalaRocks18 with Pkmn Heart Gold, the game crashes about 10 minutes and occurs an error when load the save.
I used the latest version of **DS-Scene Rom Tool** to path, but didn't work.
I have the **DSiMenuPlusPlus v5.3.1** with **nds-bootstrap v0.10.2**.
Any help?

**Comment by Robz8** [comment]
Use the xDelta patch.
