### ISSUE TITLE
Top screen is purple and black.

### ISSUE THREAD

**Issue by anuserlol** [Robz8/DSiMenuPlusPlus#60]
The bottom screen seems to work normal except of the colors, that are like red/purple and the start font is black so it's almost impossible to read it, also the top screen is a gradient between purple and black, also, I don't know if this is a bug or not, but the top font with the name and the hour looks completely different from the one of the bottom screen, and when I press left to  change the rom I want to load, it shows a little smiley face and the hour goes to the right.

I'm using and old 3ds (XL) with the DSiMenu++ Launcher from the CIA.
Also, it doesn't show any DSiWare.

**Comment by Robz8** [comment]
Those are all known bugs, except for the gradient background, which is being changed in the next version.
Also, you can't run DSiWare on 3DS with DSiMenu++.
