### ISSUE TITLE
My dsiware does not appear

### ISSUE THREAD

**Issue by LuisSant** [Robz8/DSiMenuPlusPlus#62]
My dsiware does not appear for some reason, i tried everything since **Dsimenu++** is my default menu, oh and i have my dsi with unlaunch + HiyaCFW

**Comment by Dimensional** [comment]
I have the same problem. I installed the cia files to my 3DS, and installed them through fbi, but they aren't showing up in the home screen. I copied the _nds folder to the root of my SD, copied the 2 boot.nds files to the root of the SD, but there are no proper instructions for the whole installation for 3DS to ensure I did anything correctly, so I'm lost. Is there anything I may have missed?

btw, I downloaded v4.4.0 (rev 1) and installed that after uninstalling and removing all files related to TWLoader.

**Comment by piratesephiroth** [comment]
apparently you need to press down on the dpad to see the dsiware

**Comment by piratesephiroth** [comment]
For the 3DS all you need is to copy the the _nds folder to the SD and to install the  3 CIAs.
The remaining files in the archive are for DSi usage only.

**Comment by Dimensional** [comment]
The latest version, v4.4.0 Rev 01, only had 2 files, the menu++, and the game booter. It's been like that since 4.3.2.

**Comment by piratesephiroth** [comment]
well then just install the launcher and it should run fine

**Comment by Dimensional** [comment]
*facepalms* If the launcher is one of the cia files, then again, they ARE installed but not showing.

**Comment by Dimensional** [comment]
That's a little oversight, not including instructions to the launcher, or having it included in the archive. :3
