### ISSUE TITLE
Does not boot up on O3DS

### ISSUE THREAD

**Issue by cdubthecoolcat** [Robz8/DSiMenuPlusPlus#63]
After I press "Start DSiMenu++" on the DSiMenu++ Launcher, the DSiMenu++ logo appears and then a white screen appears and never changes.  I'm on an O3DS with version 4.3.0 of DSiMenu++.

**Comment by Multimegamander** [comment]
do you have CFW?

**Comment by cdubthecoolcat** [comment]
Yes, I'm on the latest version of luma

**Comment by Robz8** [comment]
Try the latest version of DSiMenu++.

**Comment by Lv44EnderShaman** [comment]
Experiencing the same issue on O3DS. Installed the latest version--4.3.1-rev02--and it only boots to a white screen after showing the splash screen. It was working with version 4.2.0 when I updated.

**Comment by tolly7654** [comment]
I am also experiencing this issue on O3DS whilst using version 5.1.0 (boxart update), but the interesting thing is that it worked correctly one time (managed to get it into pokemon platinum), but once I restarted my console this issue started occurring.
