### ISSUE TITLE
Possible other uses for notification LED

### ISSUE THREAD

**Issue by RandomMan25XX** [Robz8/DSiMenuPlusPlus#64]
Dunno why, but I kinda want the notification LED to be used as an access indicator, have it flash yellow as it loads the ROM, green if the game launches and during every time it reads from the SD card while playing, and red if it fails

**Comment by piratesephiroth** [comment]
doesn't it kinda do that already?

**Comment by RandomMan25XX** [comment]
Not really, at least not what I've seen, it just pulses like when you get a notification for streetpass/spotpass

**Comment by WalaRocks18** [comment]
interesting indeed

**Comment by piratesephiroth** [comment]
It only works like that on the DSi. The "Emulated" DS mode on the 3DS doesn't have access to the LEDs.

**Comment by NightYoshi370** [comment]
@Robz8 this should be closed as well, since the question was already answered
