### ISSUE TITLE
ROM Icon gets misplaced onto START text

### ISSUE THREAD

**Issue by OmeletHopper** [Robz8/DSiMenuPlusPlus#66]
I guess I don't exactly know how to explain this, but a picture says a thousand words:
![photo on 6-22-18 at 10 12 am](https://user-images.githubusercontent.com/29617853/41784277-d785b22c-7604-11e8-984a-8addebcd3a07.jpg)
![photo on 6-22-18 at 10 12 am 2](https://user-images.githubusercontent.com/29617853/41784278-d86bc974-7604-11e8-8bd2-90736325b5f3.jpg)
Sometimes it becomes the color of the text, other times it overwrites the text:
![photo on 6-22-18 at 10 14 am](https://user-images.githubusercontent.com/29617853/41784362-1a2abe24-7605-11e8-8ad8-e47f6db2c014.jpg)
Also worth mentioning that I've noticed (so far) it only happens on titles without backgrounds.

**Comment by Robz8** [comment]
That only happens sometimes, and sadly, I can't fix that, due to the graphics lib I'm using being a bit buggy.
