### ISSUE TITLE
R4i Gold RTS autoload whitescreen

### ISSUE THREAD

**Issue by bkacjios** [Robz8/DSiMenuPlusPlus#69]
Hey, I'm trying to get this to work on my R4i Gold RTS flash card on my original DS lite. I copied the files in `Flashcard autoboot/R4iDSN, R4i Gold RTS, R4 Ultra` to the root of my SD card, but now when I turn on my DS I just get a white screen.

If I use the original `_DS_MENU.DAT` I can manually load `BOOT_fc.nds` through the original flashcard menu and it works fine.

Am I doing something wrong?

**Comment by Robz8** [comment]
You'll have to stick with the manual method, as I can't fix it without owning an R4i Gold Rts.

**Comment by bkacjios** [comment]
Is there something I could do to help debug this? I have devkitARM installed on my Linux drive, so if you could maybe give me a starting point on where to look at, I'd be happy to investigate.
