### ISSUE TITLE
Touchscreen Doesn't Work When Launching Homebrew

### ISSUE THREAD

**Issue by jetlego** [Robz8/DSiMenuPlusPlus#72]
System information: DSi version 1.4.5, HiyaCFW v1.3.1, nds-bootstrap version 0.9.2, DsiMenu++ version 4.3.2

When launching homebrew titles such as DScraft, Eigenmath, and pocketphysics with the Y button from DSiMenu++, no touchscreen input seems to register, while all physical buttons and animations seem to work perfectly. This issue has persisted since nds-bootstrap version 0.7.3, which was the first when I attempted running homebrew. I also found that launching these titles from the homebrew menu installed from a TIA in SDNAND has this same issue, if that helps.

While looking through the Gbatemp thread on DSiMenu++, it seems Robz8 is [aware](https://gbatemp.net/threads/ds-i-3ds-dsimenu-ds-i-menu-replacement.472200/page-43#post-7910819) of this issue, though looking through the issues here and on nds-bootstrap, I failed to find any issue which covered this particular bug. 

If this has already been covered elsewhere or should be made on the nds-bootstrap github page instead, I can close this issue.

EDIT: for some reason, with pocket physics the touch screen appears to work, but for no other homebrew that I tested did it work.

**Comment by piratesephiroth** [comment]
I think homebrew support isn't a priority at the moment

**Comment by jetlego** [comment]
I am not certain why, but with the latest bootstrap launching the homebrew with A allows for full functionality of the touchscreen.
