### ISSUE TITLE
Editing Certain System Settings Causes Crash 

### ISSUE THREAD

**Issue by jetlego** [Robz8/DSiMenuPlusPlus#73]
System information: DSi  version 1.4.5U, HiyaCFW v1.3.1, nds-bootstrap version 0.9.2, DsiMenu++ version 4.3.2

After following the directions [here](http://dsi.cfw.guide/more/replacing-system-menu/) to replace the DSi menu with DSiMenu++ and enable internal DSiWare titles to be loaded, the argv file for system settings appeared to be incorrectly made stating that "argv cannot be found" in DSiMenu++" when hovered over. Upon opening the argv file, I noticed that while the argv file had a path of "sd:/title/00030015/484e4245/content/00000002.app", there was only a 00000003.app in that specified folder in SDNAND. This is probably unrelated to the bug itself, but i'm not familiar enough with how DSiMenu++ works to know for certain.

However, after editing the argv file to point at the correct file, I noticed that while most settings such as brightness were able to be edited without problem, changing some settings in system settings caused system settings to crash with the message "An error has occurred. Press and hold the Power Button to turn the system off. Please see the Nintendo DSi Operations Manual for help troubleshooting". In particular, these are Date, Time, and Wireless Communications. They only cause a crash when tapping the "Ok" button after modifying the setting. For both Date and Time, simply pressing the power button to go back to DSiMenu++ will still save the settings. In contrast, whether HiyaCFW autoboot title is turned on of off, wireless settings seem to revert whenever the settings app was opened from DSiMenu++ and the wireless communications setting changed.  

I also attempted to change the name of the .app file for system settings from 00000003.app to 00000002.app as that was the name suggested in the argv file for system settings, however this caused the system settings folder to be entirely deleted, and I had to restore the title from a NAND backup.

I have 167 blocks remaining in SDNAND according to data management, so I do not believe this is due to DSiWare taking up more space on the "internal memory" than the DSi system thinks it has.

**Comment by Robz8** [comment]
This isn't a DSiMenu++ issue. It's a HiyaCFW issue.
Also, it may not be possible to solve it without making a System Settings replacement.

**Comment by jetlego** [comment]
Though this is off topic, does this mean that there is no way to enable wireless communications on a DSi with HiyaCFW if it is turned off? 

Additionally, where should this issue be reported? I noticed that your fork of HiyaCFW is much further ahead of shutterbug2000's which hasn't been updated in almost a year, but for some reason I cannot post bug reports on your fork.
