### ISSUE TITLE
Original cart games crash

### ISSUE THREAD

**Issue by Barawer** [Robz8/DSiMenuPlusPlus#74]
I tried running some games from my original carts via DSiMenuPlusPlus on my 3ds, but i just get a luma crash error. while booting from the home menu the games works fine. Booting roms also works fine.
I'm using a New 3DS, Sys ver 11.6, latest DSiMenu. tried it with a couple of carts and i got the same thing. Will attach an image of the error. I also get a white screen after trying to change settings, not sure if thats connected somehow.
I tried the same thing on my DSi, no error there, but i'm using an older version, i need to update.
![2018-06-28 19 45 36](https://user-images.githubusercontent.com/23010906/42049114-af2d70c2-7b0d-11e8-85a1-83a6342901a2.jpg)

**Comment by Robz8** [comment]
This issue will be fixed in the next version, by having NTR Launcher launching the Slot-1 cart.
