### ISSUE TITLE
roms folder completely broken or moody

### ISSUE THREAD

**Issue by Xrayxout** [Robz8/DSiMenuPlusPlus#75]
every time I just drag any rom (nes, nds, and gba) and put it in my dsi, it fails to boot. only when I delete the roms, the menu works again. the times it DOES load with the rom, I can load the rom and play BUT, if it turn the dsi off and back on, it crashes every time until I delete the rom.

**Comment by Robz8** [comment]
There's probably an issue with your SD card.

**Comment by Xrayxout** [comment]
what is my sd card SUPPOSE to have?

**Comment by piratesephiroth** [comment]
you should test it with h2testw

**Comment by Xrayxout** [comment]
what is that even suppose to do?
I tested it and, it gave me 15088 MByte
