### ISSUE TITLE
Top screen is either black or white during DS games

### ISSUE THREAD

**Issue by aidinzolghadr** [Robz8/DSiMenuPlusPlus#78]
Hi,

I just installed this (and the launcher) but whenever I run any DS game, the top screen is either complete black or complete white.

Also first few times I tried to run the DSiMenuPlusPlus from the launcher, it froze.

Thanks.

**Comment by Robz8** [comment]
What DS games in particular?

**Comment by aidinzolghadr** [comment]
Picross.

**Comment by aidinzolghadr** [comment]
Also I tried Shiren the Wanderer and ran just fine.

**Comment by Robz8** [comment]
Picross I think, is the only game with this issue. Might be due to AP though.
