### ISSUE TITLE
[Bug] foreign region icon string prints garbage

### ISSUE THREAD

**Issue by knight-ryu12** [Robz8/DSiMenuPlusPlus#79]
For example of Japanese rom (Which doesn't have English string at all) It'll print out garbage (Possibly ref to #13)

Japanese/All foreign string is encoded with UTF-16LE.

**Comment by NightYoshi370** [comment]
This is a clone of #13, use that instead

**Comment by knight-ryu12** [comment]
Not strictly No.
This is due to other reason.

2018年7月14日(土) 8:36 NightYoshi370 <notifications@github.com>:
