### ISSUE TITLE
ACWW almost working!

### ISSUE THREAD

**Issue by malek78i** [Robz8/DSiMenuPlusPlus#83]
Hey Guys!

I just tested the new release of DSiMenu++ with ACWW (EUR) DS Rom. The Game almost works perfectly, except these 2 Things:
·The Audio is cracking
·After 1-2 Minutes, the Hour bell is ringing with a short white screen before.

If you fix this then the DSiMenu++ is a success. If its happened only on my DSi, please submit a troubleshooting.

Thank you!

**Comment by ahezard** [comment]
Please submit this issue there : https://github.com/ahezard/nds-bootstrap/issues

**Comment by NightYoshi370** [comment]
@Robz8 this is another issue with NDS-Bootstrap, and not DSiMenu++
