### ISSUE TITLE
Launching NDS Roms from Menu returns to 3DS home screen.

### ISSUE THREAD

**Issue by TechdudeGames** [Robz8/DSiMenuPlusPlus#86]
While I was using DSiMenu++ I noticed that if I tried running any NDS ROM on my N2DS that it would kick me back out to the home menu. Initially when you select the rom to run the screen goes black like  it wants to try, but NDS Bootstrap never loads up.

I have found a workaround by launching the ROM and having it register as the last ran ROM. Then, using DSiMenu++Launcher’s run last used ROM option, NDS bootstrap initializes and runs the rom normally as if then original launcher kickstarted the process.

**Comment by Robz8** [comment]
Sounds like you have an outdated version of DSiMenu++.
Please update to the latest version, as it now loads bootstrap without rebooting the system.
