### ISSUE TITLE
Help! Dsi Menu ++ Doesn't Boot.

### ISSUE THREAD

**Issue by MarioMax05** [Robz8/DSiMenuPlusPlus#87]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [# ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [# ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.4
- [ 11.7.40]  < 11.4

### DSiMenu++ version

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [v1.1.0 ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Steps to reproduce

1. I open dsi menu
2. i click start dsi menu
3. it says an error has occured when it should boot up

**Comment by Robz8** [comment]
If you're using EmuNAND, please follow [this](https://3ds.hacks.guide/move-emunand) guide.
Also, the version you specified is the Launcher version, not the DSiMenu++ version.
