### ISSUE TITLE
Mario Kart DS and Mario Party DS (and possibly other roms?) won't load levels sometimes

### ISSUE THREAD

**Issue by derkalaender** [Robz8/DSiMenuPlusPlus#89]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [X]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release _[v1.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[v4.4.0 (Rev 01)]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Mario Kart DS and Mario Party DS should load everything normal and it should be playable.

### Actual behaviour

For example, in a cup in Mario Kart DS, I can play the first two courses normally, but once the third is loaded, the screen just stays black. It even happened in the intro once: The 3DS suddenly crashed and the screen went black (but this time the music continued, although really distorted). Sometimes this happens while loading the fourth course, sometimes while loading the first one. It's really random. This also happens in Mario Party DS when loading minigames. Sometimes it works for the first few levels/courses/whatever but it always happens right before I have a chance to finish e.g. a cup in Mario Kart DS, which makes playing Mario Kart or Mario Party impossible and thus rendering DSiMenu++ useless in that regard.
(I can't use R+L+B+DPad-Down either once it's crashed, but I can exit out of DSiMenu++ by pressing the home button. So I think that this is a crash in ndsbootstrap, but not in the whole system.)

I don't know if this is the case with other games, as I haven't tried to play other games.
I have tried playing with original roms extracted from 3 different cards, I have tried it with the roms being trimmed (which allows Mario Kart to load into the RAM which is now possible with the newest update; I was hoping this would fix the problem), but still the same problem.
This is not happening with my DSi.

### Steps to reproduce

1. Launch game (3DS)
2. Play it for a while

**Comment by Robz8** [comment]
Are you sure you're using the latest nds-bootstrap on 3DS?

**Comment by derkalaender** [comment]
Yes I'm 100% sure I'm using the latest version. I have already reinstalled it several times. I have also tried to use the nightly version with the same results.

**Comment by Robz8** [comment]
Can you try 0.10.0?

**Comment by Robz8** [comment]
Just tried MKDS with nds-bootstrap v0.10.1, and all the courses loaded just load fine.
It's possible your ROMs somehow got corrupted.

**Comment by derkalaender** [comment]
No, my ROM can't be corrupted. I just extracted it from my mkds cart with GodMode9. It runs in my R4i just fine. The exact same ROM also works with my DSi with no issues. There has to be another cause for this.

**Comment by Robz8** [comment]
Can you try nds-bootstrap 0.10.0, and see if the issue is still there?

**Comment by dubbz82** [comment]
Can you post md5/crc/sha1 values if your rom is untrimmed?  This would rule out a potential bad dump

**Comment by derkalaender** [comment]
The issue happens with every version of nds-bootstrap, including 0.10.0.

The untrimmed dump of MKDS (Europe (German)) has the following values:
CRC32: 94E8127E
CRC64: BAF8ECA96BEDF722
SHA256: D1DD7A96E6C8C912FAAC2E4ACCB83682DE0F42BAC34F1AD5313D6CB78FB8D225
SHA1: CE97D9B43F0D3CA0D48B781983E8A16F6393378F
