### ISSUE TITLE
Lock's Quest - game does not open, it stays on white screen

### ISSUE THREAD

**Issue by SkynoDore** [Robz8/DSiMenuPlusPlus#90]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ x]  Old 3DS
- [x]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ x]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [x ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [x ]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [11.7 ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [4.4.0 ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Actual behaviour
does not open, it stays on white screen

### Steps to reproduce

1.open the game
2.
3.

**Comment by Robz8** [comment]
As the issue template has stated, any issue involving games/apps should be posted at nds-bootstrap's issue tracker.
Also, the DSiMenu++ Launcher version you specified is the 3DS firmware version, not the version for DSiMenu++ Launcher.
