### ISSUE TITLE
R4i-SDHC support?

### ISSUE THREAD

**Issue by lavanoid** [Robz8/DSiMenuPlusPlus#92]
Is there any plans on supporting flashcart autoboot for the R4i-SDHC (r4i-sdhc.com) ?

**Comment by lavanoid** [comment]
The R4i-SDHC is known to be a bit troublesome with booting R4.dat files that aren't from the official website, though I found this which allows people to run YSMenu by renaming it as R4.dat and making some hex edits: https://gbatemp.net/threads/ysmenu-for-r4-sdhc.187663/

I don't know if this will be of any use to you? I can confirm the hex edits work.

**Comment by lavanoid** [comment]
[R4_YSMENU.zip](https://github.com/Robz8/DSiMenuPlusPlus/files/2170853/R4_YSMENU.zip)

**Comment by Robz8** [comment]
DSiMenu++ uses YSMenu to load ROMs, so to use YSMenu to autoboot DSiMenu++ wouldn't work.
Besides, having DSiMenu++ boot YSMenu breaks ROM loading from there, for some reason.
