### ISSUE TITLE
Golden Sun DarK Dawn is not working 

### ISSUE THREAD

**Issue by demjurd** [Robz8/DSiMenuPlusPlus#93]
Hi, the game "Golden Sun Dark Dawn" got in dark screen when start.
I got the last version of dsimenu plus plus V5.00 please fix this problem in the next att.

**Comment by Robz8** [comment]
We have no idea what the issue is for Dark Dawn.
Also, please post in https://github.com/ahezard/nds-bootstrap/issues next time there's an issue related to a DS ROM on the SD card.
