### ISSUE TITLE
crashing on exiting dsi menu ++ settings

### ISSUE THREAD

**Issue by forsterp** [Robz8/DSiMenuPlusPlus#94]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [ ]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [X]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [ ]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [X]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [X]  >= 11.4
- [ ]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [X]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[5.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead
Error:
ARM9
prefech Abort (svcBreak)

### Steps to reproduce

1. going into dsi menu ++ settings
2. chanching some parameter
3. Exit with B, crashing and shut down the console

**Comment by thenets** [comment]
Same error here. Using o3DS with Luma.

**Comment by Robz8** [comment]
Turn on game patching in Luma settings to fix the issue.

**Comment by forsterp** [comment]
Is that somewhere montioned? If not you should.

**Comment by Robz8** [comment]
It's mentioned in the first post of the GBATemp thread.
