### ISSUE TITLE
GBA games visible in Games List

### ISSUE THREAD

**Issue by NoMod-Programming** [Robz8/DSiMenuPlusPlus#97]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [X]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [X]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

### DSiMenu++ version

Tell us which versions you are using:

- [X]  Latest release _[5.1.0]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Request

Would like to see the ability to run GBA games from the same games list in which nds, NES, and other games are visible from.

**Comment by Robz8** [comment]
GBARunner2 doesn't support argv yet.
argv is used for the emulators to start the selected ROM in DSiMenu++.

**Comment by NightYoshi370** [comment]
Since this can't be fixed from our side, we'll close the issue.
If the devs ever add argv, we'll reopen this issue
