### ISSUE TITLE
How do i Switch Dsi++ setting tabs with non working L+R?

### ISSUE THREAD

**Issue by janflano** [Robz8/DSiMenuPlusPlus#98]
### Your console

Tell us which console do you have:

- [ ]  DS Phat
- [ ]  DS Lite
- [x]  DSi
- [ ]  DSi XL
- [ ]  Old 3DS
- [ ]  Old 3DS XL
- [ ]  Old 2DS
- [ ]  New 3DS
- [ ]  New 3DS XL
- [ ]  New 2DS XL

### CFW and configuration

Tell us which CFW do you have:

DSi:

- [x]  HiyaCFW
- [ ]  Not using CFW / DSiWarehax

3DS/2DS:

- [ ]  Luma3DS
- [ ]  Rei-Six
- [ ]  Other CFW [specify]
- [ ]  Older CFW

### 3DS console version (ignore, if you're using DS/DSi)

Tell us which version do you have:

- [ ]  >= 11.4
- [x]  < 11.4

### DSiMenu++ Launcher version (ignore, if you're using DS/DSi)

This launches DSiMenu++ on 3DS/2DS.

Tell us which versions you are using:

- [ ]  Latest release _[please specify version]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### DSiMenu++ version

Tell us which versions you are using:

- [x]  Latest release _[5.10]_
- [ ]  I've compiled myself _[insert here commit hash]_
- [ ]  Old release _[please specify version]_

### Expected behaviour
switching settings tab
Tell us what should happen
switching settings tab
### Actual behaviour
nothing
Tell us what happens instead
nothing
### Steps to reproduce

1.have non working L+R
2.
3.

**Comment by Robz8** [comment]
You can't. The only way is with L+R.

**Comment by BobMarleyisapokemoninLOZ** [comment]
Could an option be added? like X/Y instead of L/R? and maybe a double tap on the D-Pad left or right for rom pages.

**Comment by piratesephiroth** [comment]
it could jump to the previous/next page when we pressed left/right at the first/last entry.

However... do you really have multiple pages of games that don't require L & R?

**Comment by RS55** [comment]
And if you add a "button swap" on the first screen to use the XY instead, both DS and DSi suffer from easily damaged LR and many play without those buttons, in the end, XY are not used in this menu in the first place

**Comment by NightYoshi370** [comment]
In my opinion, if X & Y aren't used at all, they could be added as a replacement for L & R

**Comment by Robz8** [comment]
In the next version, X+Y will be used alongside L+R.

**Comment by janflano** [comment]
thx
